version: "3.6"

services:
  web:
    image: uclalibrary/ursus
    hostname: ursus
    depends_on:
      - db
      - dockerhost
    env_file:
      - ./dotenv.sample
    environment:
      DATABASE_HOST: db
      IIIF_URL: https://californica-test.library.ucla.edu/concern/works
      THUMBNAIL_BASE_URL: http://californica-test.library.ucla.edu
      SOLR_URL: "$URSUS_SOLR_URL"
      SOLR_TEST_URL: "$URSUS_SOLR_TEST_URL"
    ports:
      - "3003:3000"
    volumes:
      - .:/ursus
      - bundle_dir:/usr/local/bundle
    working_dir: /ursus
    stdin_open: true
    tty: true
  db:
    image: mysql:5.6
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
volumes:
  bundle_dir:
  mysql_data:
